name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: kapricorn-media/github/.github/workflows/zig-release-package.yaml@main
    with:
      zig-version: 0.10.1
      package-name: yorstory
      zig-build-command: package
      package-subdir: server
