name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    uses: kapricorn-media/github/.github/workflows/zig-release.yaml@main
    with:
      zig-version: 0.10.0
      package-name: yorstory
