name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    uses: kapricorn-media/github/.github/workflows/release-0.10.1.yaml@main
    with:
      package-name: yorstory